#exemplo que consta nas páginas 6 a 10 do slide da aula
#coded by stickman
 

#comandos DDL para criar o esquema e a tabela pessoa
CREATE SCHEMA POSTO;

CREATE TABLE POSTO.PESSOA (
	CPF INT UNSIGNED
);

#comandos DDL para alterar a estrutura da tabela pessoa
ALTER TABLE POSTO.PESSOA ADD ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY; #adiciono uma chave
ALTER TABLE POSTO.PESSOA CHANGE CPF CPF BIGINT; #altero uma chave existente

#comandos DDL para criar as tabelas combustível e abastece
CREATE TABLE POSTO.COMBUSTIVEL(
	ID INT UNSIGNED AUTO_INCREMENT,
    PRECO DECIMAL(5,2) NOT NULL,
    PRECO_PARA_FUNCIONARIO DECIMAL(5,2),
    DESCRICAO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE POSTO.ABASTECE(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    VALOR DECIMAL(5,2) NOT NULL,
    DATA_ABASTECIMENTO DATE,
    ID_PESSOA INT UNSIGNED,
    ID_COMBUSTIVEL INT UNSIGNED,
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID),
    FOREIGN KEY(ID_COMBUSTIVEL) REFERENCES COMBUSTIVEL(ID)	
);

#comandos DDL para indexar campos das tabelas pessoa e combustivel
USE POSTO;
CREATE INDEX INDEX_PESSOA_ID ON POSTO.PESSOA(ID);
CREATE INDEX INDEX_COMBUSTIVEL_ID ON POSTO.COMBUSTIVEL(ID);

#criando um trigger para que o desconto de 5% para os funcionarios do posto seja aplicado. 
USE POSTO;
CREATE TRIGGER PTRIGGER_COMBUSTIVEL_DESCONTO BEFORE INSERT ON POSTO.COMBUSTIVEL
FOR EACH ROW
SET NEW.PRECO_PARA_FUNCIONARIO = (NEW.PRECO * 0.95);

#insiro registos nas tabelas pessoa, combustível e abastece
INSERT INTO POSTO.PESSOA(CPF) VALUES(01254785698);
INSERT INTO POSTO.PESSOA(CPF) VALUES(58759865875);
INSERT INTO POSTO.PESSOA(CPF) VALUES(87542569875);
INSERT INTO POSTO.PESSOA(CPF) VALUES(25489653214);
INSERT INTO POSTO.PESSOA(CPF) VALUES(01547853698);
INSERT INTO POSTO.COMBUSTIVEL(PRECO, DESCRICAO) VALUES(5.49, 'GASOLINA');
INSERT INTO POSTO.COMBUSTIVEL(PRECO, DESCRICAO) VALUES(3.98, 'ETANOL');
INSERT INTO POSTO.COMBUSTIVEL(PRECO, DESCRICAO) VALUES(7.90, 'GASOLINA ADITIVADA');
INSERT INTO POSTO.COMBUSTIVEL(PRECO, DESCRICAO) VALUES(3.30, 'DIESEL');
INSERT INTO POSTO.COMBUSTIVEL(PRECO, DESCRICAO) VALUES(5.50, 'DIESEL EXTRA PURO');
INSERT INTO POSTO.ABASTECE(VALOR, DATA_ABASTECIMENTO, ID_PESSOA, ID_COMBUSTIVEL) VALUES (100.00, 20210616,5,1);
INSERT INTO POSTO.ABASTECE(VALOR, DATA_ABASTECIMENTO, ID_PESSOA, ID_COMBUSTIVEL) VALUES (180.00, 20210513,4,2);
INSERT INTO POSTO.ABASTECE(VALOR, DATA_ABASTECIMENTO, ID_PESSOA, ID_COMBUSTIVEL) VALUES (50.00, 20210105,3,3);
INSERT INTO POSTO.ABASTECE(VALOR, DATA_ABASTECIMENTO, ID_PESSOA, ID_COMBUSTIVEL) VALUES (25.00, 20210225,2,4);
INSERT INTO POSTO.ABASTECE(VALOR, DATA_ABASTECIMENTO, ID_PESSOA, ID_COMBUSTIVEL) VALUES (150.00, 20210304,1,5);

#select padrão, para listar todos os elementos das tabelas pessoa, combustível e abastece
SELECT * FROM POSTO.PESSOA;
SELECT * FROM POSTO.COMBUSTIVEL;
SELECT * FROM POSTO.ABASTECE;

#select que retorna o cpf do primeiro cliente
SELECT POSTO.PESSOA.CPF
FROM POSTO.PESSOA
WHERE POSTO.PESSOA.ID=1;

#select que retorna o combustível que cada pessoa abasteceu seu veículo e a data que o abastecimento foi feito, de acordo com o seu cpf
SELECT POSTO.PESSOA.CPF, POSTO.COMBUSTIVEL.DESCRICAO, POSTO.ABASTECE.DATA_ABASTECIMENTO
FROM POSTO.PESSOA, POSTO.COMBUSTIVEL, POSTO.ABASTECE
WHERE POSTO.PESSOA.ID = POSTO.ABASTECE.ID_PESSOA AND POSTO.COMBUSTIVEL.ID = POSTO.ABASTECE.ID_COMBUSTIVEL;

